/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InSearch_Search;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import login.LoginPage;

/**
 *
 * @author hamma
 */
public class hasilSearchLogin extends javax.swing.JFrame {

    public static String id;
    
    public hasilSearchLogin() {
        initComponents();
        populateJTable();
        
    }

    detailBukuLogin detail = new detailBukuLogin();
    
    

    
/**
     * Creates new form hasilSearch
     */

        
        
        public void populateJTable(){
        QueryLogin q = new QueryLogin();
        //String cari = kolomCari.getText();
        ArrayList<buku> list = q.BindTable();
        String[] columnName = {"Gambar","ID","Judul","Stok","Letak"};
        Object[][] rows = new Object[list.size()][6];
        for(int i = 0; i < list.size(); i++){
            if(list.get(i).getImage() != null){
                ImageIcon image = new ImageIcon(new ImageIcon(list.get(i).getImage()).getImage()
                .getScaledInstance(100, 100, Image.SCALE_SMOOTH));
                
            rows[i][0] = image;
            }
            else{
                rows[i][0] = null;
            }
            rows[i][1] = list.get(i).getId_buku();
            rows[i][2] = list.get(i).getJudul();
            rows[i][3] = list.get(i).getStok();
            rows[i][4] = list.get(i).getLetak();
        }
        
        Model mod = new Model(columnName, rows);
        jTable1.setModel(mod);
        jTable1.setRowHeight(120);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(150);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        kolomCari = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bookmarkButton = new javax.swing.JButton();
        riwayatButton = new javax.swing.JButton();
        bookingButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(1600,900);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 204, 255));

        kolomCari.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        kolomCari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kolomCari.setHighlighter(null);
        kolomCari.setSelectionColor(new java.awt.Color(255, 255, 255));
        kolomCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomCariActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon("D:\\Hammam File\\Telkom University\\SEMESTER 5\\RPL Implementasi\\loupe 20px.png")); // NOI18N
        searchButton.setText("Search");
        searchButton.setOpaque(false);
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setText("InSearch");

        LogoutButton.setBackground(new java.awt.Color(255, 255, 255));
        LogoutButton.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        LogoutButton.setText("LOGOUT");
        LogoutButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Hammam File\\Telkom University\\SEMESTER 5\\RPL Implementasi\\profile-user 20px.png")); // NOI18N
        jLabel2.setText("jLabel2");

        bookmarkButton.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        bookmarkButton.setText("Bookmark");
        bookmarkButton.setBorderPainted(false);
        bookmarkButton.setContentAreaFilled(false);
        bookmarkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookmarkButtonMouseClicked(evt);
            }
        });

        riwayatButton.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        riwayatButton.setText("Riwayat");
        riwayatButton.setBorderPainted(false);
        riwayatButton.setContentAreaFilled(false);
        riwayatButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatButtonMouseClicked(evt);
            }
        });

        bookingButton.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        bookingButton.setText("Booking");
        bookingButton.setBorderPainted(false);
        bookingButton.setContentAreaFilled(false);
        bookingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(338, 338, 338)
                .addComponent(kolomCari, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(riwayatButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookmarkButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kolomCari))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LogoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookmarkButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(riwayatButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookingButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        kolomCari.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1576, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        Connection conn = koneksi.koneksiDb();
        Statement st;
        ResultSet rs;
        
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        ImageIcon image1 = (ImageIcon)model.getValueAt(index, 0);
        Image image2 = image1.getImage().getScaledInstance(detail.gambarSampul.getWidth()
                , detail.gambarSampul.getHeight()
                , Image.SCALE_SMOOTH);
        ImageIcon image3 = new ImageIcon(image2);
        id = model.getValueAt(index, 1).toString();
        String judul = model.getValueAt(index, 2).toString();
        String stok = model.getValueAt(index, 3).toString();
        String letak = model.getValueAt(index, 4).toString();
        String penulis = null;
        String penerbit = null;
        String ISBN = null;
        int tahun = 0;
        String kategori = null;
        String bahasa = null;
        int halaman = 0;
        String deskripsi = null;
        
        try{
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM `buku` WHERE `id_buku` = "+id+"");
            while (rs.next()) {
                penulis = rs.getString("penulis");
                penerbit = rs.getString("penerbit");
                ISBN = rs.getString("noISBN");
                tahun = rs.getInt("tahun");
                kategori = rs.getString("kategori");
                bahasa = rs.getString("bahasa");
                halaman = rs.getInt("halaman");
                deskripsi = rs.getString("deskripsi");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Query.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        detail.setVisible(true);
        detail.pack();
        detail.setLocationRelativeTo(null);
        detail.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        detailBukuLogin.jLabel13.setText(LoginPage.getUsername());
        detail.gambarSampul.setIcon(image3);
        detail.judulTxt.setText(judul);
        detail.penulisTxt.setText(penulis);
        detail.penerbitTxt.setText(penerbit);
        detail.ISBNTxt.setText(ISBN);
        detail.TahunTxt.setText(String.valueOf(tahun));
        detail.kategoriTxt.setText(kategori);
        detail.bahasaTxt.setText(bahasa);
        detail.halamanTxt.setText(String.valueOf(halaman));
        detail.stokTxt.setText(stok);
        detail.letakTxt.setText(letak);
        detail.deskripsiTxt.setText(deskripsi);
        
        this.dispose();
        insertToRiwayat();
        
    }//GEN-LAST:event_jTable1MouseClicked

    public void insertToRiwayat(){
        Connection conn = koneksi.koneksiDb();
        Statement st;
        ResultSet rs;
        PreparedStatement ps;
        
        String username = jLabel2.getText();
        int id_user = 0;
        int id_buku = hasilSearchLogin.getId();
        
        try{
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM `user` WHERE `username` = '"+username+"'");
            while (rs.next()) {
                id_user = rs.getInt("id_user");
            }
            try {
                String sql = "INSERT INTO `riwayat` (`id_riwayat`, `id_user`, `id_buku`, `waktu_akses`) VALUES (NULL, '"+id_user+"', '"+id_buku+"', current_timestamp())";
                ps = conn.prepareStatement(sql);
                ps.executeUpdate();
                        //JOptionPane.showMessageDialog(null, "Buku berhasil ditambahkan ke bookmark!");
                        
            } catch (SQLException ex) {
                Logger.getLogger(Query.class.getName()).log(Level.SEVERE, null, ex);
                        
            }
        } catch (SQLException ex) {
            Logger.getLogger(Query.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static int getId() {
        return Integer.parseInt(id);
    }

    
    
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void kolomCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomCariActionPerformed

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:
        populateJTable();
    }//GEN-LAST:event_searchButtonMouseClicked

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        SearchUI2 search = new SearchUI2();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void bookmarkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookmarkButtonMouseClicked
        // TODO add your handling code here:
        bookmark bm = new bookmark();
        bm.setVisible(true);
        bookmark.jLabel2.setText(LoginPage.getUsername());
        bm.populateJTable();
        bm.pack();
        bm.setLocationRelativeTo(null);
        bm.setDefaultCloseOperation(SearchAfterLogin.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_bookmarkButtonMouseClicked

    private void riwayatButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatButtonMouseClicked
        // TODO add your handling code here:
        riwayat rw = new riwayat();
        rw.setVisible(true);
        riwayat.jLabel2.setText(LoginPage.getUsername());
        rw.populateJTable();
        rw.pack();
        rw.setLocationRelativeTo(null);
        rw.setDefaultCloseOperation(SearchAfterLogin.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_riwayatButtonMouseClicked

    private void bookingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingButtonMouseClicked
        // TODO add your handling code here:
        booking bk = new booking();
        bk.setVisible(true);
        booking.jLabel2.setText(LoginPage.getUsername());
        bk.populateJTable();
        bk.pack();
        bk.setLocationRelativeTo(null);
        bk.setDefaultCloseOperation(SearchAfterLogin.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_bookingButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hasilSearchLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hasilSearchLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hasilSearchLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hasilSearchLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hasilSearchLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton bookingButton;
    private javax.swing.JButton bookmarkButton;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTextField kolomCari;
    private javax.swing.JButton riwayatButton;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
